import type { SurahTimingIndex } from './timings';

// Generated by scripts/publish_timing_index.py after the strict verified-data gate.
export const VERIFIED_TIMING_INDEXES: Readonly<
  Partial<Record<number, SurahTimingIndex>>
> = {};
