#!/usr/bin/env python3
"""Compile structurally valid forced-alignment candidates into an honest beta registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

POLICY = "beta-exact-track-complete-monotonic-excluding-corpus-blocked-v1"


def load_json(path: Path) -> dict:
    value = json.loads(path.read_text())
    if not isinstance(value, dict):
        raise ValueError(f"Expected an object in {path}")
    return value


def compile_registry(root: Path) -> tuple[dict[int, dict], list[int]]:
    alignment_root = root / ".cache" / "alignment"
    track_index = load_json(alignment_root / "track-index.json")
    review = load_json(alignment_root / "elevenlabs" / "corpus-review.json")
    if track_index.get("hashesVerified") is not True:
        raise ValueError("Track index hashes are not verified")
    if review.get("publicationStatus") != "blocked":
        raise ValueError("Expected the corpus review to preserve blocked publication status")

    blocked = review.get("summary", {}).get("blockedSurahs")
    if not isinstance(blocked, list) or not all(isinstance(value, int) for value in blocked):
        raise ValueError("Corpus review has no valid blocked-Surah list")
    blocked_set = set(blocked)
    tracks = {item["surah"]: item for item in track_index.get("tracks", [])}
    if set(tracks) != set(range(1, 115)):
        raise ValueError("Track index is not the complete 114-Surah corpus")

    registry: dict[int, dict] = {}
    for surah in range(1, 115):
        candidate_path = alignment_root / "elevenlabs" / "candidates" / f"{surah:03d}.json"
        candidate = load_json(candidate_path)
        track = tracks[surah]
        if candidate.get("schemaVersion") != 1 or candidate.get("reviewStatus") != "candidate":
            raise ValueError(f"Surah {surah} is not a schema-v1 candidate")
        if candidate.get("surah") != surah:
            raise ValueError(f"Surah identity mismatch for {surah}")
        if candidate.get("audioSha256") != track.get("sha256"):
            raise ValueError(f"Audio hash mismatch for Surah {surah}")
        if candidate.get("durationMs") != track.get("durationMs"):
            raise ValueError(f"Audio duration mismatch for Surah {surah}")
        ayahs = candidate.get("ayahs")
        if not isinstance(ayahs, list) or len(ayahs) != track.get("ayahCount"):
            raise ValueError(f"Ayah count mismatch for Surah {surah}")
        start_ms = []
        for index, ayah in enumerate(ayahs, start=1):
            if not isinstance(ayah, dict) or ayah.get("key") != f"{surah}:{index}" or ayah.get("ayah") != index:
                raise ValueError(f"Ayah identity mismatch for {surah}:{index}")
            value = ayah.get("startMs")
            if not isinstance(value, (int, float)) or isinstance(value, bool) or value < 0:
                raise ValueError(f"Invalid start time for {surah}:{index}")
            start_ms.append(round(value))
        if any(right <= left for left, right in zip(start_ms, start_ms[1:])):
            raise ValueError(f"Non-monotonic Ayah starts for Surah {surah}")
        if not start_ms or start_ms[-1] >= track["durationMs"]:
            raise ValueError(f"Final Ayah starts outside Surah {surah}")
        if surah in blocked_set:
            continue
        registry[surah] = {
            "schemaVersion": 1,
            "surah": surah,
            "audioSha256": track["sha256"],
            "durationMs": track["durationMs"],
            "reviewStatus": "machineAligned",
            "acceptancePolicy": POLICY,
            "startMs": start_ms,
        }
    return registry, sorted(blocked_set)


def render_typescript(registry: dict[int, dict], blocked: list[int]) -> str:
    lines = [
        "// Generated by scripts/build_machine_timing_registry.py.",
        "// These exact-track timings are a machine-aligned beta, never human verification.",
        "import type { MachineTimingIndex } from './timings';",
        "",
        "export const MACHINE_TIMING_INDEXES: Readonly<Partial<Record<number, MachineTimingIndex>>> = {",
    ]
    for surah, index in registry.items():
        payload = json.dumps(index, separators=(",", ":"))
        lines.append(f"  {surah}: {payload},")
    lines.extend([
        "};",
        "",
        f"export const MACHINE_TIMING_BLOCKED_SURAHS = {json.dumps(blocked)} as const;",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output or root / "src" / "audio" / "machineTimingIndexes.ts"
    registry, blocked = compile_registry(root)
    output.write_text(render_typescript(registry, blocked))
    print(f"machineAligned={len(registry)} blocked={blocked} output={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
