#!/usr/bin/env python3
"""Publish a fully verified timing index into the static Expo runtime registry."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

from validate_timing_index import validate

ROOT = Path(__file__).resolve().parents[1]
TIMING_DIR = ROOT / "src" / "audio" / "timingData"
REGISTRY_PATH = ROOT / "src" / "audio" / "verifiedTimingIndexes.ts"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)


def publication_payload(timing: dict[str, Any]) -> dict[str, Any]:
    source = timing["source"]
    published_source = {
        key: source[key]
        for key in ("method", "model", "generationConfig", "generatedAt", "lastReviewedAt")
        if key in source
    }
    payload: dict[str, Any] = {
        "schemaVersion": 1,
        "surah": timing["surah"],
        "audioSha256": timing["audioSha256"],
        "durationMs": timing["durationMs"],
        "source": published_source,
        "reviewStatus": "verified",
        "ayahs": [
            {
                "key": point["key"],
                "ayah": point["ayah"],
                "startMs": point["startMs"],
                "confidence": point["confidence"],
                "reviewStatus": "verified",
            }
            for point in timing["ayahs"]
        ],
    }
    if "prelude" in timing:
        payload["prelude"] = timing["prelude"]
    return payload


def rebuild_registry(track_index: dict[str, Any]) -> None:
    manifests: list[tuple[int, Path]] = []
    for path in sorted(TIMING_DIR.glob("*.json")):
        timing = json.loads(path.read_text(encoding="utf-8"))
        validate(timing, track_index, True)
        manifests.append((timing["surah"], path))

    lines = ["import type { SurahTimingIndex } from './timings';"]
    if manifests:
        lines.append("")
        for surah, path in manifests:
            lines.append(f"import timing{surah:03d} from './timingData/{path.name}';")
    lines.extend(
        [
            "",
            "// Generated by scripts/publish_timing_index.py after the strict verified-data gate.",
            "export const VERIFIED_TIMING_INDEXES: Readonly<",
            "  Partial<Record<number, SurahTimingIndex>>",
            "> = {",
        ]
    )
    for surah, _ in manifests:
        lines.append(f"  {surah}: timing{surah:03d} as unknown as SurahTimingIndex,")
    lines.extend(["};", ""])
    atomic_write(REGISTRY_PATH, "\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("timing", type=Path)
    parser.add_argument(
        "--track-index", type=Path, default=Path(".cache/alignment/track-index.json")
    )
    args = parser.parse_args()

    timing = json.loads(args.timing.read_text(encoding="utf-8"))
    track_index = json.loads(args.track_index.read_text(encoding="utf-8"))
    try:
        validate(timing, track_index, True)
    except ValueError as error:
        raise SystemExit(f"Not publishable: {error}") from error

    payload = publication_payload(timing)
    destination = TIMING_DIR / f"{timing['surah']:03d}.json"
    atomic_write(destination, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    rebuild_registry(track_index)
    print(f"published={destination} surah={timing['surah']} ayahs={len(timing['ayahs'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
